[project]
name = "homework-grading-system"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aliyun-python-sdk-core==2.15.2",
    "aliyun-python-sdk-ocr==1.0.19",
    "celery==5.5.1",
    "dashscope==1.25.17",
    "fastapi==0.115.11",
    "gunicorn==23.0.0",
    "loguru==0.7.3",
    "numpy==1.26.4",
    "opencv-python==4.10.0.84",
    "passlib[bcrypt]==1.7.4",
    "pillow==11.1.0",
    "psycopg2-binary==2.9.10",
    "pybreaker==1.1.0",
    "pydantic-settings==2.6.1",
    "python-dotenv==1.0.1",
    "python-jose[cryptography]==3.3.0",
    "python-multipart==0.0.16",
    "redis==5.2.1",
    "sqlalchemy==2.0.36",
    "sympy==1.13.3",
    "uvicorn==0.34.0",
]
